services:
  back:
    image: jafber/frogwatch-back
    environment:
      - RASPI_TOKEN
    build:
      context: ./back
      dockerfile: Dockerfile

  front:
    image: nginx
    volumes:
      - ./front:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:80
