services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile

  front:
    image: nginx
    volumes:
      - ./front:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80