version: '3.8'
services:
  raspi:
    build: .
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - WS_URL=wss://frogwatch.jan-berndt.de/ws/raspi
      - RASPI_TOKEN
    devices:
      - "/dev/vchiq:/dev/vchiq"
    privileged: true
