[program:frogwatch]
directory=/home/pi/frogwatch/raspi
environment=PYTHONPATH=/usr/lib/python3/dist-packages
command=/bin/bash -c 'set -a && source secret.env && exec .venv/bin/python __init__.py'
autostart=true
autorestart=true
stderr_logfile=/var/log/frogwatch/raspi.err.log
stdout_logfile=/var/log/frogwatch/raspi.out.log
