#!/bin/bash

gist_id='REPLACE'
logfile='/var/log/cron/dyndns'
date >> $logfile
echo "refresh with public ip $(curl --silent http://ipv4.icanhazip.com)" >> $logfile
echo >> $logfile
gh config set editor saveip
gh gist edit $gist_id -f ipv4.txt
gh config set editor nano
